#!/bin/bash

# Read variables passed on by Git
read OLDREV NEWREV REFNAME

GIT_EXEC="${GIT_EXEC:-$(which git)}"
REPO="${REPO:-$(basename $PWD)}"
CALLSIGN="${CALLSIGN:-$REPO}"
HIPCHAT_COLOR="${HIPCHAT_COLOR:-'yellow'}"

# User is commiter of either last or first commit
NULLREV="0000000000000000000000000000000000000000"
[[ "$NEWREV" == "$NULLREV" ]] && USER_REV="$OLDREV" || USER_REV="$NEWREV"
USER=$($GIT_EXEC log -1 $USER_REV --format="%aN")
USER_EMAIL=$($GIT_EXEC log -1 $USER_REV --format="%aE")
BRANCH="${REFNAME#refs/heads/}"

# Set up links
USER_LINK="<a href='mailto:$USER_EMAIL'>$USER</a>"
BRANCH_LINK="<a href='https://$PHAB/source/$REPO/browse/$BRANCH/'>$BRANCH</a>"
REPO_LINK="<a href='https://$PHAB/source/$REPO/'>$REPO</a>"

# Construct message
if [[ "$OLDREV" == "$NULLREV" ]]
then
  MSG="$USER_LINK created branch $BRANCH_LINK of $REPO_LINK"
  HIPCHAT_COLOR="green"
elif [[ "$NEWREV" == "$NULLREV" ]]
then
  MSG="$USER_LINK deleted branch $BRANCH of $REPO_LINK"
  HIPCHAT_COLOR="red"
else
  TITLE="$USER_LINK pushed to branch $BRANCH_LINK of $REPO_LINK"
  FMT_STR="- %s (<a href='https://$PHAB/r$CALLSIGN%H'>%h</a>)"

  LOG=$($GIT_EXEC log $OLDREV..$NEWREV --format="$FMT_STR")
  MSG="$TITLE\n$LOG"
fi

# Send to HipChat
echo -e "$MSG" | $HIPCHAT_SCRIPT > /dev/null
