#!/bin/bash

# Read variables passed on by Git
read OLDREV NEWREV REFNAME

GIT_EXEC="${GIT_EXEC:-$(which git)}"
REPO="${REPO:-$(basename $PWD)}"
CALLSIGN="${CALLSIGN:-$REPO}"

# User is commiter of either last or first commit
NULLREV="0000000000000000000000000000000000000000"
[[ "$NEWREV" == "$NULLREV" ]] && USER_REV="$OLDREV" || USER_REV="$NEWREV"
USER=$($GIT_EXEC log -1 $USER_REV --format="%aN")
BRANCH="${REFNAME#refs/heads/}"

# Set up links
BRANCH_LINK="[$BRANCH](https://$PHAB/source/$REPO/browse/$BRANCH/)"
REPO_LINK="[$REPO](https://$PHAB/source/$REPO/)"

# Construct message
if [[ "$OLDREV" == "$NULLREV" ]]
then
  MSG="$USER created branch $BRANCH_LINK of $REPO_LINK"
  ATTACHMENTS="[]"
elif [[ "$NEWREV" == "$NULLREV" ]]
then
  MSG="$USER deleted branch $BRANCH of $REPO_LINK"
  ATTACHMENTS="[]"
else
  MSG="$USER pushed to branch $BRANCH_LINK of $REPO_LINK"

  ATTACHMENTS=$($GIT_EXEC log $OLDREV..$NEWREV \
    --pretty=format:"{\"text\":\"%s ([%h](https://$PHAB/r$CALLSIGN%H))\"}," $@ \
    | perl -pe 'BEGIN{print "["}; END{print "]"}' \
    | perl -pe 's/},]/}]/')
fi

BODY="{\"text\":\"$MSG\",\"channel\":\"$ROCKETCHAT_CHANNEL\",\"attachments\": $ATTACHMENTS}"

# Send to RocketChat incoming webhook
curl -s -X POST -H 'Content-Type: application/json' -d "$BODY" \
  $ROCKETCHAT_WEBHOOK_URL > /dev/null
