#!/bin/bash

# Read variables passed on by Git
read OLDREV NEWREV REFNAME

GIT_EXEC="${GIT_EXEC:-$(which git)}"
REPO="${REPO:-$(basename $PWD)}"
CALLSIGN="${CALLSIGN:-$REPO}"

# User is commiter of either last or first commit
NULLREV="0000000000000000000000000000000000000000"
[[ "$NEWREV" == "$NULLREV" ]] && USER_REV="$OLDREV" || USER_REV="$NEWREV"
USER=$($GIT_EXEC log -1 $USER_REV --format="%aN")
BRANCH="${REFNAME#refs/heads/}"

# Set up links
BRANCH_LINK="[$BRANCH](https://$PHAB/source/$REPO/browse/$BRANCH/)"
REPO_LINK="[$REPO](https://$PHAB/source/$REPO/)"

# Construct message
if [[ "$OLDREV" == "$NULLREV" ]]
then
  MSG="$USER created branch $BRANCH_LINK of $REPO_LINK"
elif [[ "$NEWREV" == "$NULLREV" ]]
then
  MSG="$USER deleted branch $BRANCH of $REPO_LINK"
else
  TITLE="$USER pushed to branch $BRANCH_LINK of $REPO_LINK"
  FMT_STR="- %s ([%h](https://$PHAB/r$CALLSIGN%H))"

  LOG=$($GIT_EXEC log $OLDREV..$NEWREV --format="$FMT_STR")
  MSG="$TITLE\n$LOG"
fi

# Send to RocketChat incoming webhook
curl -s -X POST -H 'Content-Type: application/json' -d "{\"text\":\"$MSG\", \"channel\":\"$ROCKETCHAT_CHANNEL\"}" $ROCKETCHAT_WEBHOOK_URL > /dev/null
